# Auto-generated by Omage Compiler
import omage as og

# Model: myAI
myAI = og.model(
    type="classifier",
    layers=[og.dense(128), og.dropout(0.2), og.dense(10)]
)

# Training: myAI
myAI.train(data, epochs=10, batch_size=32)

# Save model
myAI.save("my_model.omg")