"""
Omage Generator — Generate Python code from AST
"""

from __future__ import annotations
from typing import Any, Dict, List


def generate_python(ast: List[Dict[str, Any]]) -> str:
    """Generate valid Python code from Omage AST"""
    lines = [
        "# Auto-generated by Omage Transpiler",
        "# Do not edit manually",
        "",
        "import omage as og",
        "",
    ]

    for node in ast:
        t = node["type"]

        # ---- variable ------------------------------------------------ #
        if t == "variable":
            name  = node["name"]
            vtype = node["var_type"]
            value = node["value"]
            kind  = node["kind"]

            if vtype == "data":
                lines.append(f'{name} = og.load({value})')
            elif vtype == "model":
                # newCreate block
                if "newCreate" in value:
                    model_type = _extract_quoted(value, "type") or "classifier"
                    layer_list = _extract_layers(value)
                    lines.append(f'{name} = og.model(')
                    lines.append(f'    type="{model_type}",')
                    lines.append(f'    layers=[{layer_list}]')
                    lines.append(f')')
                else:
                    lines.append(f'{name} = og.load_model({value})')
            elif vtype == "result":
                lines.append(f'{name} = None')
            else:
                # number, text, bool, func …
                py_val = _convert_value(value)
                if kind == "lock":
                    lines.append(f'# lock (immutable)')
                lines.append(f'{name} = {py_val}')

            lines.append("")

        # ---- show ---------------------------------------------------- #
        elif t == "show":
            lines.append(f'print({node["content"]})')

        # ---- train --------------------------------------------------- #
        elif t == "train":
            name = node["model"]
            lines.append(f'# Training {name}')
            lines.append(f'{name}.train(data=data, epochs=10, batch_size=32)')
            lines.append("")

        # ---- evaluate ------------------------------------------------ #
        elif t == "evaluate":
            lines.append(f'{node["model"]}.evaluate({node["data"]})')

        # ---- save ---------------------------------------------------- #
        elif t == "save":
            lines.append(f'{node["model"]}.save("{node["path"]}")')

        # ---- predict ------------------------------------------------- #
        elif t == "predict":
            inp    = node["input"]
            model  = node["model"]
            result = node.get("result_var")
            if result:
                lines.append(f'{result} = {model}.predict({inp})')
            else:
                lines.append(f'{model}.predict({inp})')

        # ---- raw Python pass-through --------------------------------- #
        elif t == "raw":
            lines.append(_convert_omage_syntax(node["code"]))

    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ #
# Helpers
# ------------------------------------------------------------------ #

def _extract_quoted(text: str, key: str) -> str:
    import re
    m = re.search(rf'{key}\s*:\s*"([^"]+)"', text)
    return m.group(1) if m else ""


def _extract_layers(value: str) -> str:
    import re
    m = re.search(r'layers\s*:\s*\[([^\]]+)\]', value)
    if not m:
        return "og.dense(128), og.dense(10)"
    raw = m.group(1).strip()
    tokens = raw.split()
    parts = []
    for tok in tokens:
        tok = tok.strip()
        if tok.startswith("dense"):
            parts.append(f"og.{tok}")
        elif tok.startswith("dropout"):
            parts.append(f"og.{tok}")
        elif tok.startswith("conv2d"):
            parts.append(f"og.{tok}")
        elif tok.startswith("flatten"):
            parts.append("og.flatten()")
        elif tok.startswith("pool"):
            parts.append(f"og.{tok}")
    return ", ".join(parts) if parts else "og.dense(128), og.dense(10)"


def _convert_value(value: str) -> str:
    """Convert Omage literal to Python literal"""
    if value == "true":  return "True"
    if value == "false": return "False"
    if value == "none":  return "None"
    return value


def _convert_omage_syntax(line: str) -> str:
    """Convert Omage-specific syntax in raw lines to Python"""
    # and/or/not are already valid Python
    # foreach (item => collection) → for item in collection:
    import re
    line = re.sub(r'foreach\s*\((\w+)\s*=>\s*(\w+)\)', r'for \1 in \2:', line)
    line = re.sub(r'foreach\s*\((\w+)\s+in\s+(\w+)\)',  r'for \1 in \2:', line)
    # show(...) → print(...)
    line = re.sub(r'\bshow\s*\(', 'print(', line)
    # none → None
    line = re.sub(r'\bnone\b', 'None', line)
    # true/false → True/False
    line = re.sub(r'\btrue\b', 'True', line)
    line = re.sub(r'\bfalse\b', 'False', line)
    return line
